### ISSUE TITLE
SPECS: Flaky specs

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#1227]
## Aktuelles Verhalten

Es gibt einzelne specs die nur zwischendurch failen. 

## Gewünschtes Verhalten

Tests sind stabil.

Tests die Flaky sind in diesem Issue als Kommentar hinzufügen.

**Comment by psunix** [comment]
Failures:

  1) MailingListsController removes two labels from existing mailing

     Failure/Error: expect(page).not_to have_content 'Vater'

       expected not to find text "Vater" in "Gruppen\nTop\nTopGroup\nToppers\nOhne Rollen\nBOTTOM LAYER\nBottom One\nBottom Two\nAnlässe\nKurse\nRechnungen\nEinstellungen\nTop Leader\nAbmelden\nTop Leader\nAbmelden\n Top\nInfo\nPersonen\nAnlässe\nKurse\nAbos\nAnfragen\nNotizen\nGelöscht\nEinstellungen\nLeaders\nNachrichten\nEinstellungen\nAbonnenten\nBearbeiten Löschen Anmelden Rechnung erstellen\n×\nAbo Leaders wurde erfolgreich aktualisiert.\n  Mailingliste\nleaders@localhost\nHerausgeber\n  MailChimp API-Schlüssel\n  MailChimp Listen-ID\n  Alle Versandadressen synchronisieren\nnein\nZusätzlicher Absender\n  Versand an Haupt E-Mail\nnein\nBevorzugte E-Mail-Labels\nVater\nAbonnenten dürfen sich selbst an/abmelden\nAbonnenten dürfen nicht auf die Mailingliste schreiben\nBeliebige Absender/-innen dürfen nicht auf die Mailingliste schreiben\nAbsender erhalten kein E-Mail als Versandbestätigung\nVersion 1.26.1\nQuellcode verfügbar unter der GNU Affero General Public License\nEntwickelt von Hitobito 2012 - 2021"

     # ./spec/features/mailing_lists_spec.rb:27:in `block (2 levels) in <top (required)>'

     # ./spec/spec_helper.rb:102:in `block (3 levels) in <top (required)>'

     # ./spec/support/feature_helpers.rb:38:in `keeping_stdout'

     # ./spec/spec_helper.rb:101:in `block (2 levels) in <top (required)>'

     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/exe/rspec:4:in `<main>'

Finished in 2 minutes 28.1 seconds (files took 3.8 seconds to load)

92 examples, 1 failure, 25 pending

Failed examples:

rspec ./spec/features/mailing_lists_spec.rb:16 # MailingListsController removes two labels from existing mailing

**Comment by kronn** [comment]
Wir brauchen einen konkreten Seed, um diesen Fehler beheben zu können. Durch Ausprobieren habe ich keinen gefunden, bei dem der Fehler auftritt. Wenn der Fehler erneut gefunden wird, bitte den Seed vermerken.

**Comment by carlobeltrame** [comment]
Habe einen Seed ergänzt
