### ISSUE TITLE
SPEC: Flaky Feature Spec Person Notes

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1230]
``` 
1) Person Notes creation adds newly created notes

     Failure/Error: expect(page).to have_content('Keine Einträge gefunden')

       expected to find text "Keine Einträge gefunden" in "RSpec::Mocks::ExpiredTestDoubleError at /groups/954199476/people/572407901\n#<Double :assignments_settings> was originally created in one example but has leaked into another example and can no longer be used. rspec-mocks' doubles are designed to only last for one example, and you need to create a new one in each example you wish to use it for.\nApplication Frames All Frames\n<class:Person>\napp/helpers/sheet/person.rb, line 54\n<module:Sheet>\napp/helpers/sheet/person.rb, line 9\n<top (required)>\napp/helpers/sheet/person.rb, line 8\nSheet::Base.controller_sheet_class\napp/helpers/sheet/base.rb, line 56\nSheet::Base.sheet_for_controller\napp/helpers/sheet/base.rb, line 45\nSheet::Base.current_sheet_class\napp/helpers/sheet/base.rb, line 41\nSheet::Base.current\napp/helpers/sheet/base.rb, line 34\n#<Class:0x00007f9719360ff8>#sheet\napp/helpers/sheet_helper.rb, line 33\n#<Class:0x00007f9719360ff8>#title\napp/helpers/sheet_helper.rb, line 18\n#<Class:0x00007f9719360ff8>#_app_views_crud_show_html_haml___2961591157367757368_70143531772060\napp/views/crud/show.html.haml, line 6\nPeopleController#render\napp/controllers/concerns/decorates_before_rendering.rb, line 35\nPeopleController#render\napp/controllers/concerns/dry_crud/render_callbacks.rb, line 24\n<class:Person>\napp/helpers/sheet/person.rb\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n        :colleagues_group_person_path,\n        if: (lambda do |_view, _group, person|\n          person.company_name?\n        end)\n    if Settings.assignments&.enabled\n      tab 'activerecord.models.assignment.other',\n          :group_person_assignments_path,\n          if: :show_details\n    end\n>>\nThis is a live shell. Type in here.\nRequest info\nRequest parameters\n{\"controller\"=>\"people\", \"action\"=>\"show\", \"group_id\"=>\"954199476\", \"id\"=>\"572407901\"}\nRack session\n(Object too large. Modify ActionDispatch::Request::Session#inspect or adjust BetterErrors.maximum_variable_inspect_size if you need to see it.)\nLocal Variables\nInstance Variables"

     # ./spec/features/person/person_notes_spec.rb:29:in `block (3 levels) in <top (required)>'

     # ./spec/spec_helper.rb:102:in `block (3 levels) in <top (required)>'

     # ./spec/support/feature_helpers.rb:38:in `keeping_stdout'

     # ./spec/spec_helper.rb:101:in `block (2 levels) in <top (required)>'

     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/exe/rspec:4:in `<main>'
```

**Comment by amaierhofer** [comment]
Mittlerweile behoben
