### ISSUE TITLE
OPS: Transifex client pull error

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#1251]
## Aktuelles Verhalten

Beim Pullen der Transifex translations während des builds kommt es zu folgender Exception:

```
 Integration build: Pulling transifex translations.
I, [2021-04-19T09:51:59.686306 #31897]  INFO -- : ** Invoke tx:pull (first_time)
I, [2021-04-19T09:51:59.686368 #31897]  INFO -- : ** Execute tx:pull
I, [2021-04-19T09:51:59.686381 #31897]  INFO -- : tx pull -f
I, [2021-04-19T09:51:59.766848 #31897]  INFO -- : Traceback (most recent call last):
I, [2021-04-19T09:51:59.766868 #31897]  INFO -- :   File "/usr/bin/tx", line 5, in <module>
I, [2021-04-19T09:51:59.766875 #31897]  INFO -- :     from pkg_resources import load_entry_point
I, [2021-04-19T09:51:59.766882 #31897]  INFO -- :   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
I, [2021-04-19T09:51:59.766889 #31897]  INFO -- :     working_set.require(__requires__)
I, [2021-04-19T09:51:59.766895 #31897]  INFO -- :   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
I, [2021-04-19T09:51:59.786323 #31897]  INFO -- :     needed = self.resolve(parse_requirements(requirements))
I, [2021-04-19T09:51:59.786343 #31897]  INFO -- :   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
I, [2021-04-19T09:51:59.786372 #31897]  INFO -- :     raise DistributionNotFound(req)
I, [2021-04-19T09:51:59.786378 #31897]  INFO -- : pkg_resources.DistributionNotFound: python-slugify==1.2.6
```

Alle Integrationsbuilds sind davon betroffen. 

Work around: INTEGRATION_BUILD Env-Var auf 0 setzen für den Build

## Gewünschtes Verhalten

Die translations können für die Integrations-Builds gepulled werden.

# Tech-Spec

- Verwendetes Installations-Script Transifex Client: https://github.com/hitobito/hitobito/blob/master/images/s2i/root/opt/bin/install-transifex
- Dockerfile: https://github.com/hitobito/hitobito/blob/master/images/s2i/Dockerfile
- Anscheinend gab es in der Vergangenheit schon mal das Problem von depricated dependencies: https://github.com/hitobito/hitobito/blob/master/images/s2i/root/opt/bin/install-transifex#L15
- Ein weiterer Grund der für ein neues Ruby Base Image spricht

**Comment by psunix** [comment]
im Hitobito core dir:

`docker build . -t hitobito-rails-dev`
`docker run -u root --mount type=bind,source="$(pwd)",target=/opt/app-root/src -it hitobito-rails-dev bash`

**Comment by psunix** [comment]
ich habe noch eine aktuelle Python Version installiert und damit den neuesten transifex-client.
lokaler build funktioniert und `scl enable rh-python38 'tx --version'` spuckt die aktuelle Version aus.
auch ein tx pull hatte funktioniert als ich noch die Rails Sourcen reingenommen habe.
