### ISSUE TITLE
SPEC: LabelFormatsController if display global is disabled hides global formats if switch is toggled

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1286]
## Current (flaky) state:

```
F

Failures:

     LabelFormatsController if display global is disabled hides global formats if switch is toggled
     Failure/Error: no_token_present? && !CorsOrigin.where(origin: origin).exists?

     NoMethodError:
       undefined method `synchronize' for nil:NilClass
     # ./vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/model_schema.rb:475:in `load_schema'
     # ./vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/model_schema.rb:362:in `attribute_types'
     # ./vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/model_schema.rb:386:in `type_for_attribute'
     # ./vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/table_metadata.rb:33:in `type'
     # ./vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/relation/predicate_builder.rb:51:in `build'
     # ./vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/relation/predicate_builder.rb:109:in `block in expand_from_hash'
     # ./vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/relation/predicate_builder.rb:68:in `each'
     # ./vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/relation/predicate_builder.rb:68:in `flat_map'
     # ./vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/relation/predicate_builder.rb:68:in `expand_from_hash'
     # ./vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/relation/predicate_builder.rb:21:in `build_from_hash'
     # ./vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/relation/where_clause_factory.rb:19:in `build'
     # ./vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/relation/query_methods.rb:656:in `where!'
     # ./vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/relation/query_methods.rb:649:in `where'
     # ./vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/querying.rb:21:in `where'
     # ./app/domain/api/cors_check.rb:30:in `no_token_declines?'
     # ./app/domain/api/cors_check.rb:18:in `allowed?'
     # ./config/initializers/cors.rb:9:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.5.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:319:in `block in allow_origin?'
     # ./vendor/bundle/ruby/2.5.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:317:in `each'
     # ./vendor/bundle/ruby/2.5.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:317:in `detect'
     # ./vendor/bundle/ruby/2.5.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:317:in `allow_origin?'
     # ./vendor/bundle/ruby/2.5.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:212:in `block in match_resource'
     # ./vendor/bundle/ruby/2.5.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:211:in `each'
     # ./vendor/bundle/ruby/2.5.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:211:in `match_resource'
     # ./vendor/bundle/ruby/2.5.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:186:in `process_cors'
     # ./vendor/bundle/ruby/2.5.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:89:in `call'
     # ./vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.4/lib/rails/engine.rb:527:in `call'
     # ./vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
     # ./vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
     # ./vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
     # ./vendor/bundle/ruby/2.5.0/gems/capybara-3.31.0/lib/capybara/server/middleware.rb:58:in `call'
     # ./vendor/bundle/ruby/2.5.0/gems/puma-4.3.5/lib/puma/configuration.rb:228:in `call'
     # ./vendor/bundle/ruby/2.5.0/gems/puma-4.3.5/lib/puma/server.rb:713:in `handle_request'
     # ./vendor/bundle/ruby/2.5.0/gems/puma-4.3.5/lib/puma/server.rb:472:in `process_client'
     # ./vendor/bundle/ruby/2.5.0/gems/puma-4.3.5/lib/puma/server.rb:328:in `block in run'
     # ./vendor/bundle/ruby/2.5.0/gems/puma-4.3.5/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
     # ------------------
     # --- Caused by: ---
     # Capybara::CapybaraError:
     #   Your application server raised an error - It has been raised in your test code because Capybara.raise_server_errors == true
     #   ./vendor/bundle/ruby/2.5.0/gems/capybara-3.31.0/lib/capybara/session.rb:160:in `raise_server_error!'

Finished in 3 minutes 8.2 seconds (files took 4.81 seconds to load)
92 examples, 1 failure, 24 pending

Failed examples:

rspec ./spec/features/label_formats_spec.rb:52 # LabelFormatsController if display global is disabled hides global formats if switch is toggled

Randomized with seed 21857
```

## Expected

```
.
```

**Comment by amaierhofer** [comment]
Mittlerweile behoben
