### ISSUE TITLE
SPEC: InvoicesController regression spec

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1302]
## Current (flaky) state:

```
Failures:
  1) InvoicesController hides invoices link when person is not authorised
     Failure/Error: expect(page.find('#page-navigation')).not_to have_link 'Rechnungen'
     
     Capybara::ElementNotFound:
       Unable to find css "#page-navigation"
     # ./vendor/bundle/ruby/2.5.0/gems/capybara-3.31.0/lib/capybara/node/finders.rb:302:in `block in synced_resolve'
     # ./vendor/bundle/ruby/2.5.0/gems/capybara-3.31.0/lib/capybara/node/base.rb:83:in `synchronize'
     # ./vendor/bundle/ruby/2.5.0/gems/capybara-3.31.0/lib/capybara/node/finders.rb:291:in `synced_resolve'
     # ./vendor/bundle/ruby/2.5.0/gems/capybara-3.31.0/lib/capybara/node/finders.rb:52:in `find'
     # ./vendor/bundle/ruby/2.5.0/gems/capybara-3.31.0/lib/capybara/session.rb:759:in `block (2 levels) in <class:Session>'
     # ./spec/features/group/invoices_controller_spec.rb:18:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/exe/rspec:4:in `<main>'
Finished in 2 minutes 19.4 seconds (files took 3.94 seconds to load)
92 examples, 1 failure, 24 pending
Failed examples:
rspec ./spec/features/group/invoices_controller_spec.rb:14 # InvoicesController hides invoices link when person is not authorised
Randomized with seed 437
```

**Comment by amaierhofer** [comment]
Mittlerweile behoben
