### ISSUE TITLE
SPEC: SearchStrategies::Sphinx#list_people as admin finds deleted, not accessible people

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1346]
## Aktuelles Verhalten

```
..................F........

Failures:

  1) SearchStrategies::Sphinx#list_people as admin finds deleted, not accessible people
     Failure/Error: expect(result).to include(@deleted_bg_member)

       expected [] to include #<Person id: 572407911, first_name: "Natalie", last_name: "Lg", company_name: nil, nickname: "Tayler"...ken: nil, show_global_label_formats: true, household_key: nil, event_feed_token: nil, tag_list: nil>
       Diff:
       @@ -1,2 +1,2 @@
       -[#<Person id: 572407911, first_name: "Natalie", last_name: "Lg", company_name: nil, nickname: "Tayler", company: false, email: "natalie.lg192@hitobito.example.com", address: nil, zip_code: nil, town: nil, country: nil, gender: nil, birthday: nil, additional_information: nil, contact_data_visible: false, created_at: "2021-07-13 15:45:35", updated_at: "2021-07-13 15:45:35", picture: nil, last_label_format_id: nil, creator_id: nil, updater_id: nil, primary_group_id: nil, authentication_token: nil, show_global_label_formats: true, household_key: nil, event_feed_token: nil, tag_list: nil>]
       +[]
     # ./spec/domain/search_strategies/sphinx_spec.rb:99:in `block (5 levels) in <top (required)>'
     # ./spec/support/sphinx_environment.rb:44:in `block (2 levels) in run_sphinx_around_example'
     # ./vendor/bundle/ruby/2.5.0/gems/thinking-sphinx-4.4.1/lib/thinking_sphinx/test.rb:34:in `run'
     # ./spec/support/sphinx_environment.rb:41:in `block in run_sphinx_around_example'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.9.1/exe/rspec:4:in `<main>'

Finished in 2 minutes 7.5 seconds (files took 7.08 seconds to load)
27 examples, 1 failure

Failed examples:

rspec ./spec/domain/search_strategies/sphinx_spec.rb:96 # SearchStrategies::Sphinx#list_people as admin finds deleted, not accessible people

Randomized with seed 18634
```

## Gewünschtes Verhalten

```
...........................
```

## Schritte zum reproduzieren

`rspec --tag sphinx=true --seed 18634`

**Comment by kronn** [comment]
Sphinx is not used anymore
