### ISSUE TITLE
SPEC: SearchStrategies::Sphinx#list_people as admin finds people without any roles

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1578]
## Aktuelles Verhalten

```
Randomized with seed 37075
....................F......

Failures:

  1) SearchStrategies::Sphinx#list_people as admin finds people without any roles
     Failure/Error: expect(result).to include(@no_role)

       expected [] to include #<Person id: 572407909, first_name: "Sandro", last_name: "Co", company_name: nil, nickname: "Marina",...obal_label_formats: true, household_key: nil, event_feed_token: nil, family_key: nil, tag_list: nil>
       Diff:
       @@ -1 +1 @@
       -[#<Person id: 572407909, first_name: "Sandro", last_name: "Co", company_name: nil, nickname: "Marina", company: false, email: "sandro.co210@hitobito.example.com", address: nil, zip_code: nil, town: nil, country: nil, gender: nil, birthday: nil, additional_information: nil, contact_data_visible: false, created_at: "2022-01-05 11:20:15.000000000 +0100", updated_at: "2022-01-05 11:20:15.000000000 +0100", picture: nil, last_label_format_id: nil, creator_id: nil, updater_id: nil, primary_group_id: nil, authentication_token: nil, show_global_label_formats: true, household_key: nil, event_feed_token: nil, family_key: nil, tag_list: nil>]
       +[]
     # ./spec/domain/search_strategies/sphinx_spec.rb:81:in `block (5 levels) in <top (required)>'
     # ./spec/support/sphinx_environment.rb:44:in `block (2 levels) in run_sphinx_around_example'
     # ./vendor/bundle/ruby/2.5.0/gems/thinking-sphinx-5.3.0/lib/thinking_sphinx/test.rb:34:in `run'
     # ./spec/support/sphinx_environment.rb:41:in `block in run_sphinx_around_example'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<main>'
```

## Gewünschtes Verhalten

`...........................`

## Schritte zum reproduzieren

`rspec --tag sphinx=true --seed 37075`

**Comment by kronn** [comment]
Sphinx is not in use anymore.
