### ISSUE TITLE
SPECS: Tags::Merger ignores nonexistent tag ids

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1850]
### Welche Spec ist fehlgeschlagen?

rspec ./spec/domain/tags/merger_spec.rb:120 # Tags::Merger merge tags ignores non existent tag ids

### Welcher Seed wurde verwendet?

16723

### Stacktrace

```
  1) Tags::Merger merge tags ignores non existent tag ids
     Failure/Error: expect(tag2_owner.reload.tags.to_a).to eq([tag1])

       expected: [#<ActsAsTaggableOn::Tag id: 42, name: "Clairvoyance 5606", taggings_count: 2>]
            got: [#<ActsAsTaggableOn::Tag id: 43, name: "Radiation Absorption 8094", taggings_count: 2>]

       (compared using ==)

       Diff:
       @@ -1 +1 @@
       -[#<ActsAsTaggableOn::Tag id: 42, name: "Clairvoyance 5606", taggings_count: 2>]
       +[#<ActsAsTaggableOn::Tag id: 43, name: "Radiation Absorption 8094", taggings_count: 2>]
     # ./spec/domain/tags/merger_spec.rb:126:in `block (3 levels) in <main>'
     # ./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<main>'

**Comment by rnestler** [comment]
Similar one:

Seed: 22065 

`rspec ./spec/domain/tags/merger_spec.rb:88 # Tags::Merger merge tags does not merge validation tags`

```
Tags::Merger .......F

  1) Tags::Merger merge tags does not merge validation tags
     Failure/Error: expect(all_tag_owner.reload.tags.to_a).to eq([tag1, tag2])

       expected: [#<ActsAsTaggableOn::Tag id: 164, name: "Adaptation 7718", taggings_count: 2>, #<ActsAsTaggableOn::Tag id: 165, name: "Energy Manipulation 9755", taggings_count: 2>]
            got: [#<ActsAsTaggableOn::Tag id: 165, name: "Energy Manipulation 9755", taggings_count: 2>, #<ActsAsTaggableOn::Tag id: 164, name: "Adaptation 7718", taggings_count: 2>]

       (compared using ==)

       Diff:
       @@ -1,3 +1,3 @@
       -[#<ActsAsTaggableOn::Tag id: 164, name: "Adaptation 7718", taggings_count: 2>,
       - #<ActsAsTaggableOn::Tag id: 165, name: "Energy Manipulation 9755", taggings_count: 2>]
       +[#<ActsAsTaggableOn::Tag id: 165, name: "Energy Manipulation 9755", taggings_count: 2>,
       + #<ActsAsTaggableOn::Tag id: 164, name: "Adaptation 7718", taggings_count: 2>]
     # ./spec/domain/tags/merger_spec.rb:95:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:140:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/rspec-core-3.13.0/exe/rspec:4:in `<main>'
```
