### ISSUE TITLE
Tests auf master branch fixen

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito#2195]
### Aktuelles Verhalten

aktuell failen auf dem CI Tests im master branch:
https://github.com/hitobito/hitobito/actions/runs/6120116244/job/16611335887
```
Failures:

  1) Dropdown::PeopleExport renders dropdown
     Failure/Error: expect(tag).to have_content 'CSV'
       expected to find text "CSV" in " Export "
     # ./spec/helpers/dropdown/people_export_spec.rb:36:in `block (3 levels) in <main>'
...

  2) Dropdown::GroupAdd renders dropdown
     Failure/Error: expect(tag).to have_content 'Group::TopGroup'
       expected to find text "Group::TopGroup" in " Gruppe erstellen "
     # ./spec/helpers/dropdown/group_add_spec.rb:30:in `block (3 levels) in <main>'
...
```

### Gewünschtes Verhalten

Fixen

### Schritte zu reproduzieren

see CI

**Comment by daniel-illi** [comment]
Die Tests failen seit einigen commits. 
Allerdings haben sie noch nie wirlich funktioniert. Es wird `is_expected.to have_selector` mit einem Block aufgerufen, der Block wird aber gar nie evaluiert :zany_face:
