### ISSUE TITLE
SPECS: Flaky Spec person tag spec

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2277]
### Welche Spec ist fehlgeschlagen?

./spec/features/person/person_tags_spec.rb:47

### Welcher Seed wurde verwendet?

41436

### Stacktrace

```
Failures:

  1) Person Tags listing user with :index_tags permission lists tags grouped by categories
     Failure/Error: expect(all('.person-tags-category').length).to eq(4)

       expected: 4
            got: 3

       (compared using ==)
     # ./spec/features/person/person_tags_spec.rb:54:in `block (4 levels) in <main>'
     # ./spec/spec_helper.rb:148:in `block (3 levels) in <top (required)>'
     # ./spec/support/feature_helpers.rb:37:in `keeping_stdout'
     # ./spec/spec_helper.rb:147:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:142:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.0.0/gems/webmock-3.19.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <main>'
     # ./vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/exe/rspec:4:in `<main>'

Finished in 2 minutes 17.9 seconds (files took 4.97 seconds to load)
155 examples, 1 failure, 26 pending

Failed examples:

rspec ./spec/features/person/person_tags_spec.rb:47 # Person Tags listing user with :index_tags permission lists tags grouped by categories
```

**Comment by amaierhofer** [comment]
Mittlerweile behoben
