### ISSUE TITLE
EVENTS: Flaky Spec

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2737]
### Welche Spec ist fehlgeschlagen?

./spec/decorators/qualification_decorator_spec.rb

### Welcher Seed wurde verwendet?

?

### Stacktrace

```
  1) QualificationDecorator without training days is nil if qualification is active
     Failure/Error: expect(qualification).to be_active
       expected `#<Qualification id: nil, person_id: nil, qualification_kind_id: 1063113981, start_at: "2024-04-10", finish_at: nil, origin: nil, qualified_at: nil>.active?` to be truthy, got false
     # ./spec/decorators/qualification_decorator_spec.rb:25:in `block (3 levels) in <top (required)>'
     # ./spec/decorators/qualification_decorator_spec.rb:21:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/testing/time_helpers.rb:169:in `travel_to'
     # ./spec/decorators/qualification_decorator_spec.rb:21:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:158:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/rspec-core-3.13.0/exe/rspec:4:in `<main>'

  2) QualificationDecorator with training days contains days and icon but no tooltip when is active and does not expire
     Failure/Error: expect(qualification).to be_active
       expected `#<Qualification id: nil, person_id: nil, qualification_kind_id: 1063113984, start_at: "2024-04-10", finish_at: nil, origin: nil, qualified_at: nil>.active?` to be truthy, got false
     # ./spec/decorators/qualification_decorator_spec.rb:45:in `block (3 levels) in <top (required)>'
     # ./spec/decorators/qualification_decorator_spec.rb:21:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/testing/time_helpers.rb:169:in `travel_to'
     # ./spec/decorators/qualification_decorator_spec.rb:21:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:158:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/rspec-core-3.13.0/exe/rspec:4:in `<main>'

  3) QualificationDecorator with training days includes open days with icon informing about expiry
     Failure/Error: expect(qualification).to be_active
       expected `#<Qualification id: nil, person_id: nil, qualification_kind_id: 1063113985, start_at: "2024-04-10", finish_at: "2024-03-23", origin: nil, qualified_at: nil>.active?` to be truthy, got false
     # ./spec/decorators/qualification_decorator_spec.rb:53:in `block (3 levels) in <top (required)>'
     # ./spec/decorators/qualification_decorator_spec.rb:21:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/testing/time_helpers.rb:169:in `travel_to'
     # ./spec/decorators/qualification_decorator_spec.rb:21:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:158:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/rspec-core-3.13.0/exe/rspec:4:in `<main>'
```

**Comment by amaierhofer** [comment]
Mittlerweile behoben
