### ISSUE TITLE
SPECS: InvoiceResource including may include items

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#2804]
### Welche Spec ist fehlgeschlagen?

 rspec ./spec/resources/invoice/reads_spec.rb:47

### Welcher Seed wurde verwendet?

10167

### Stacktrace

```
  1) InvoiceResource including may include items
     Failure/Error: expect(item.name).to eq "pins"

       expected: "pins"
            got: "pens"

       (compared using ==)
     # ./spec/resources/invoice/reads_spec.rb:51:in `block (3 levels) in <top (required)>'
     # ./spec/support/resource_spec_helper.rb:24:in `block (4 levels) in <module:ResourceSpecHelper>'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti.rb:33:in `with_context'
     # ./spec/support/resource_spec_helper.rb:24:in `block (3 levels) in <module:ResourceSpecHelper>'
     # ./spec/support/resource_spec_helper.rb:23:in `block (2 levels) in <module:ResourceSpecHelper>'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti_spec_helpers-1.1.0/lib/graphiti_spec_helpers/rspec.rb:13:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti-1.3.9/lib/graphiti.rb:33:in `with_context'
     # ./vendor/bundle/ruby/3.2.0/gems/graphiti_spec_helpers-1.1.0/lib/graphiti_spec_helpers/rspec.rb:12:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:154:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/rspec-core-3.13.0/exe/rspec:4:in `<main>'

**Comment by rnestler** [comment]
https://github.com/hitobito/hitobito/actions/runs/10685193223/job/29617407125?pr=2805
