### ISSUE TITLE
Niceql NameError

### ISSUE THREAD

**Issue by matclou** [hitobito/hitobito#3024]
### Aktuelles Verhalten

Hi,

while trying to run the dockerfile within Docker desktop I encounter an error message in line 160 of the File (RUN bash -vxc "${BUILD_SCRIPT:-"echo 'no BUILD_SCRIPT provided'"}") - does anyone have an idea where this comes from?

```
RAILS_DB_ADAPTER=nulldb bundle exec rake assets:precompile
+ RAILS_DB_ADAPTER=nulldb
+ bundle exec rake assets:precompile
rake aborted!
NameError: uninitialized constant Niceql (NameError)
/app-src/config/initializers/niceql.rb:3:in `<main>'
/app-src/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.8/lib/rails/engine.rb:681:in `block in load_config_initializer'
/app-src/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:205:in `instrument'
/app-src/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.8/lib/rails/engine.rb:680:in `load_config_initializer'
/app-src/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.8/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
/app-src/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.8/lib/rails/engine.rb:633:in `each'
/app-src/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.8/lib/rails/engine.rb:633:in `block in <class:Engine>'
/app-src/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in `instance_exec'
/app-src/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in `run'
/app-src/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:61:in `block in run_initializers'
/app-src/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:50:in `each'
/app-src/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:50:in `tsort_each_child'
/app-src/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:60:in `run_initializers'
/app-src/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.8/lib/rails/application.rb:391:in `initialize!'
/app-src/config/environment.rb:5:in `<main>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/app-src/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/app-src/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
/app-src/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.8/lib/rails/application.rb:367:in `require_environment!'
/app-src/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.8/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/app-src/vendor/bundle/ruby/3.2.0/gems/airbrake-13.0.4/lib/airbrake/rake.rb:17:in `execute'
/app-src/vendor/bundle/ruby/3.2.0/gems/sprockets-rails-3.5.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'
/app-src/vendor/bundle/ruby/3.2.0/gems/airbrake-13.0.4/lib/airbrake/rake.rb:17:in `execute'
/app-src/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.5.22/lib/bundler/cli.rb:455:in `exec'
/usr/local/bundle/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.22/lib/bundler/cli.rb:35:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/bundle/gems/bundler-2.5.22/lib/bundler/cli.rb:29:in `start'
/usr/local/bundle/gems/bundler-2.5.22/exe/bundle:28:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.5.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.5.22/exe/bundle:20:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
Tasks: TOP => environment
(See full trace by running task with --trace) 
```

### Gewünschtes Verhalten

No error message while trying to install ;-)

### Schritte zu reproduzieren

Clone Git-Repository and run Dockerfile.

**Comment by kronn** [comment]
Sorry for that, fixed with 633870b93
