### ISSUE TITLE
SPECS: People::HouseholdList#people_without_household_in_batches with limited people scope respects limit

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#3093]
### Welche Spec ist fehlgeschlagen?

rspec ./spec/domain/people/household_list_spec.rb:30 # People::HouseholdList#people_without_household_in_batches with limited people scope respects limit

### Welcher Seed wurde verwendet?

51293

### Stacktrace

```
People::HouseholdList ..F........

  1) People::HouseholdList#people_without_household_in_batches with limited people scope respects limit
     Failure/Error: expect(list).to contain_exactly([scope.first])

       expected collection contained:  [[#<Person id: 572408706, first_name: "Medine", last_name: "Lichtenhagen", company_name: nil, nickname: "Luis", company: false, email: "medine.lichtenhagen1534@hitobito.example.com", address: nil, zip_code: nil, town: nil, country: nil, gender: nil, birthday: nil, additional_information: nil, contact_data_visible: false, created_at: "2024-12-18 17:13:54.954108000 +0100", updated_at: "2024-12-18 17:13:54.954108000 +0100", last_label_format_id: nil, creator_id: nil, updater_id: nil, primary_group_i...mats: true, household_key: nil, event_feed_token: nil, family_key: nil, reset_password_sent_to: nil, two_factor_authentication: nil, encrypted_two_fa_secret: nil, language: "de", privacy_policy_accepted_at: nil, minimized_at: nil, self_registration_reason_id: nil, self_registration_reason_custom_text: nil, inactivity_block_warning_sent_at: nil, blocked_at: nil, membership_verify_token: "JnBN29o1R23wu8J5Sw61fBz2", street: nil, housenumber: nil, address_care_of: nil, postbox: nil, tag_list: nil>]]
       actual collection contained:    [[#<Person id: 572408707, first_name: "Hermine", last_name: "Rach", company_name: nil, nickname: "Jon", company: false, email: "hermine.rach1535@hitobito.example.com", address: nil, zip_code: nil, town: nil, country: nil, gender: nil, birthday: nil, additional_information: nil, contact_data_visible: false, created_at: "2024-12-18 17:13:54.959885000 +0100", updated_at: "2024-12-18 17:13:54.959885000 +0100", last_label_format_id: nil, creator_id: nil, updater_id: nil, primary_group_id: nil, authent...mats: true, household_key: nil, event_feed_token: nil, family_key: nil, reset_password_sent_to: nil, two_factor_authentication: nil, encrypted_two_fa_secret: nil, language: "de", privacy_policy_accepted_at: nil, minimized_at: nil, self_registration_reason_id: nil, self_registration_reason_custom_text: nil, inactivity_block_warning_sent_at: nil, blocked_at: nil, membership_verify_token: "JdL2LuyomwG7NLZgB99BrfDs", street: nil, housenumber: nil, address_care_of: nil, postbox: nil, tag_list: nil>]]
       the missing elements were:      [[#<Person id: 572408706, first_name: "Medine", last_name: "Lichtenhagen", company_name: nil, nickname: "Luis", company: false, email: "medine.lichtenhagen1534@hitobito.example.com", address: nil, zip_code: nil, town: nil, country: nil, gender: nil, birthday: nil, additional_information: nil, contact_data_visible: false, created_at: "2024-12-18 17:13:54.954108000 +0100", updated_at: "2024-12-18 17:13:54.954108000 +0100", last_label_format_id: nil, creator_id: nil, updater_id: nil, primary_group_i...mats: true, household_key: nil, event_feed_token: nil, family_key: nil, reset_password_sent_to: nil, two_factor_authentication: nil, encrypted_two_fa_secret: nil, language: "de", privacy_policy_accepted_at: nil, minimized_at: nil, self_registration_reason_id: nil, self_registration_reason_custom_text: nil, inactivity_block_warning_sent_at: nil, blocked_at: nil, membership_verify_token: "JnBN29o1R23wu8J5Sw61fBz2", street: nil, housenumber: nil, address_care_of: nil, postbox: nil, tag_list: nil>]]
       the extra elements were:        [[#<Person id: 572408707, first_name: "Hermine", last_name: "Rach", company_name: nil, nickname: "Jon", company: false, email: "hermine.rach1535@hitobito.example.com", address: nil, zip_code: nil, town: nil, country: nil, gender: nil, birthday: nil, additional_information: nil, contact_data_visible: false, created_at: "2024-12-18 17:13:54.959885000 +0100", updated_at: "2024-12-18 17:13:54.959885000 +0100", last_label_format_id: nil, creator_id: nil, updater_id: nil, primary_group_id: nil, authent...mats: true, household_key: nil, event_feed_token: nil, family_key: nil, reset_password_sent_to: nil, two_factor_authentication: nil, encrypted_two_fa_secret: nil, language: "de", privacy_policy_accepted_at: nil, minimized_at: nil, self_registration_reason_id: nil, self_registration_reason_custom_text: nil, inactivity_block_warning_sent_at: nil, blocked_at: nil, membership_verify_token: "JdL2LuyomwG7NLZgB99BrfDs", street: nil, housenumber: nil, address_care_of: nil, postbox: nil, tag_list: nil>]]
     # ./spec/domain/people/household_list_spec.rb:31:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:144:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/3.2.0/gems/rspec-core-3.13.0/exe/rspec:4:in `<main>'

**Comment by codez** [comment]
Ich denke das Problem ist, dass die Personen *eines* Haushalts keine feste Reihenfolge haben und halt mal die eine Person, mal die andere zuerst im Subarray auftaucht.

**Comment by amaierhofer** [comment]
fixed mit dd186e76a4ad3802ab7ab1202e81c3524f02dde9
