### ISSUE TITLE
"invalid byte sequence in UTF-8" bei Login via /users/sign_in.json

### ISSUE THREAD

**Issue by hupf** [hitobito/hitobito#398]
Errbit Fehler:
https://errbit.puzzle.ch/apps/529c60a2de77482d71027b0a/problems/59ca7fc50c4ec2009c4b76cc

Kann mit einem Passwort mit Sonderzeichen (z.B. "î") reproduziert werden:
http://localhost:3000/users/sign_in.json?person[email]=foo@puzzle.ch&person[password]=%ee

```
ArgumentError in Devise::SessionsController#new
invalid byte sequence in UTF-8

activesupport (4.2.8) lib/active_support/core_ext/object/blank.rb:117:in `==='
activesupport (4.2.8) lib/active_support/core_ext/object/blank.rb:117:in `blank?'
activesupport (4.2.8) lib/active_support/core_ext/object/blank.rb:24:in `present?'
devise (3.5.10) lib/devise/models/database_authenticatable.rb:43:in `password='
activerecord (4.2.8) lib/active_record/attribute_assignment.rb:54:in `public_send'
activerecord (4.2.8) lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
activerecord (4.2.8) lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
actionpack (4.2.8) lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'
actionpack (4.2.8) lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'
activerecord (4.2.8) lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
activerecord (4.2.8) lib/active_record/core.rb:566:in `init_attributes'
activerecord (4.2.8) lib/active_record/core.rb:281:in `initialize'
activerecord (4.2.8) lib/active_record/inheritance.rb:61:in `new'
activerecord (4.2.8) lib/active_record/inheritance.rb:61:in `new'
devise (3.5.10) app/controllers/devise/sessions_controller.rb:9:in `new'
actionpack (4.2.8) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.8) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.8) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.8) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.8) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.8) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.8) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.8) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.8) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.8) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.8) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.8) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.8) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.8) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.8) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.8) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.8) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.8) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.8) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.8) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.8) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.8) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.8) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.8) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.8) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.8) lib/action_dispatch/routing/route_set.rb:74:in `call'
actionpack (4.2.8) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.8) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.8) lib/action_dispatch/routing/mapper.rb:49:in `serve'
actionpack (4.2.8) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.8) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.8) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.8) lib/action_dispatch/routing/route_set.rb:817:in `call'
bullet (5.5.1) lib/bullet/rack.rb:12:in `call'
http_accept_language (2.1.0) lib/http_accept_language/middleware.rb:14:in `call'
request_profiler (0.0.4) lib/rack/request_profiler.rb:24:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (1.6.5) lib/rack/etag.rb:24:in `call'
rack (1.6.5) lib/rack/deflater.rb:35:in `call'
rack (1.6.5) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.5) lib/rack/head.rb:13:in `call'
remotipart (1.3.1) lib/remotipart/middleware.rb:32:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.5) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.5) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.8) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.8) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.8) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.8) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
airbrake (4.3.4) lib/airbrake/rails/middleware.rb:13:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.8) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.8) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.8) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.8) lib/rails/rack/logger.rb:20:in `call'
quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
request_store (1.3.2) lib/request_store/middleware.rb:9:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.5) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.8) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.5) lib/rack/lock.rb:17:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/static.rb:120:in `call'
rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
airbrake (4.3.4) lib/airbrake/user_informer.rb:16:in `_call'
airbrake (4.3.4) lib/airbrake/user_informer.rb:12:in `call'
railties (4.2.8) lib/rails/engine.rb:518:in `call'
railties (4.2.8) lib/rails/application.rb:165:in `call'
rack (1.6.5) lib/rack/content_length.rb:15:in `call'
thin (1.5.1) lib/thin/connection.rb:81:in `block in pre_process'
thin (1.5.1) lib/thin/connection.rb:79:in `catch'
thin (1.5.1) lib/thin/connection.rb:79:in `pre_process'
thin (1.5.1) lib/thin/connection.rb:54:in `process'
thin (1.5.1) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run_machine'
eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run'
thin (1.5.1) lib/thin/backends/base.rb:63:in `start'
thin (1.5.1) lib/thin/server.rb:159:in `start'
rack (1.6.5) lib/rack/handler/thin.rb:19:in `run'
rack (1.6.5) lib/rack/server.rb:286:in `start'
railties (4.2.8) lib/rails/commands/server.rb:80:in `start'
bin/commands.rb:49:in `block in <top (required)>'
bin/commands.rb:40:in `tap'
bin/commands.rb:40:in `<top (required)>'
bin/rails:6:in `require_relative'
bin/rails:6:in `<main>'
```

Tritt nicht auf bei einem normalen Zeichen (200er):
http://localhost:3000/users/sign_in.json?person[email]=foo@puzzle.ch&person[password]=i

Tritt auch nicht auf bei einem POST über das Login Form.

**Comment by RolandStuder** [comment]
Schliess dies aufgrund von Inaktivität.
