### ISSUE TITLE
Standardisierung Mail-Versand (SMTP)

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#441]
Der Mailversand soll so angepasst werden das dieser mit Standard-SMTP Server erfolgen kann. 

# Error Handling
Die Mailer sollen neu mit einem SMTP Error Handling versehen werden. Nimmt ein SMTP Server das Mail aus irgendwelchem Grund nicht entgegen, wird eine Exception in der Webapp geworfen. 
Neu soll in einem solchen Fall eine Fehlermeldung per Mail an den Absender gehen. Geht eine Mail an mehrere Empfänger und schlägt eine der Adressen fehl, so soll das Mail trotzdem an die anderen gültigen Adressen versendet werden. Für die failenden Adressen wird eine entsprechende Nachricht an den Absender geschickt.

# Bulk-Send
Heute werden einzelne Mails an teilweise hunderte oder tausende Empfänger versendet. Konventionen besagen das eine Mail grundsätzlich an nicht mehr als 15 Empfänger gesendet werden soll. 
Neu sollen die Mails über ein Bulk-Send gesendet werden. Das Senden kann in diesem Fall auch paralel erfolgen.

# Logging
Falls mit vertretbarem Aufwand möglich soll ein einfaches Mailversand-Logging realisiert werden.

**Comment by psunix** [comment]
Test Mailversand via Appuio SMTP Server und ungültiger Domain:

TestMailer#test: processed outbound mail in 572.6ms
Net::SMTPServerBusy: 450 4.1.2 <gitssichernid@gitsnidneienei.ch>: Recipient address rejected: Domain not found

	from /opt/rh/rh-ruby22/root/usr/share/ruby/net/smtp.rb:964:in `check_response'
	from /opt/rh/rh-ruby22/root/usr/share/ruby/net/smtp.rb:933:in `getok'
	from /opt/rh/rh-ruby22/root/usr/share/ruby/net/smtp.rb:869:in `rcptto'
	from /opt/rh/rh-ruby22/root/usr/share/ruby/net/smtp.rb:850:in `block in rcptto_list'
	from /opt/rh/rh-ruby22/root/usr/share/ruby/net/smtp.rb:848:in `each'
	from /opt/rh/rh-ruby22/root/usr/share/ruby/net/smtp.rb:848:in `rcptto_list'
	from /opt/rh/rh-ruby22/root/usr/share/ruby/net/smtp.rb:663:in `send_message'
	from /opt/app-root/src/bundle/ruby/gems/mail-2.6.4/lib/mail/network/delivery_methods/smtp.rb:114:in `block in deliver!'
	from /opt/rh/rh-ruby22/root/usr/share/ruby/net/smtp.rb:521:in `start'
	from /opt/app-root/src/bundle/ruby/gems/mail-2.6.4/lib/mail/network/delivery_methods/smtp.rb:113:in `deliver!'
	from /opt/app-root/src/bundle/ruby/gems/mail-2.6.4/lib/mail/message.rb:253:in `deliver!'
	from /opt/app-root/src/bundle/ruby/gems/actionmailer-4.2.8/lib/action_mailer/message_delivery.rb:77:in `deliver_now!'
	from (irb):2
	from /opt/app-root/src/bundle/ruby/gems/railties-4.2.8/lib/rails/commands/console.rb:110:in `start'
	from /opt/app-root/src/bundle/ruby/gems/railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
	from /opt/app-root/src/bin/commands.rb:31:in `<top (required)>'
	from bin/rails:6:in `require_relative'

**Comment by psunix** [comment]
@kronn und ich haben uns gerade noch zum Error Handling ausgetauscht und folgendes festgelegt:

**Comment by psunix** [comment]
Bei pbs haben die meisten Listen unter 100 Empfänger. Ein paar wenige haben mehr (bis max. 1500)

 102,
 107,
 330,
 362,
 375,
 428,
 486,
 747,
 1320,
 1336,
 1464
