### ISSUE TITLE
404 errors für Missing Asset file im production log

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito#452]
im production log von pbs tauchen immer wieder diese 404 errors auf. 
sollten assets nicht immer direkt vom apache server gehandelt werden? auch wenn diese nicht existieren? so wird immer eine exception erzeugt was etwas unnötig erscheint.

```
rails: [df-fd-4735-df-fdf] Started GET "/apple-touch-icon-precomposed.png" for ::ffff:85.1.1.1 at 2018-02-05 12:03:25 +0100
rails: [ca06a4d5-d75c-4735-bbfd-deb2efcd998d] 
rails: ActionController::RoutingError (No route matches [GET] "/apple-touch-icon-precomposed.png"):
rails:   bundle/ruby/gems/actionpack-4.2.8/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
rails:   bundle/ruby/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
rails:   bundle/ruby/gems/railties-4.2.8/lib/rails/rack/logger.rb:38:in `call_app'
rails:   bundle/ruby/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `block in call'
rails:   bundle/ruby/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
rails:   bundle/ruby/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:26:in `tagged'
rails:   bundle/ruby/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `tagged'
rails:   bundle/ruby/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `call'
rails:   bundle/ruby/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
rails:   bundle/ruby/gems/actionpack-4.2.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
rails:   bundle/ruby/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
rails:   bundle/ruby/gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'
rails:   bundle/ruby/gems/activesupport-4.2.8/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rails:   bundle/ruby/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
rails:   bundle/ruby/gems/airbrake-4.3.4/lib/airbrake/user_informer.rb:16:in `_call'
rails:   bundle/ruby/gems/airbrake-4.3.4/lib/airbrake/user_informer.rb:12:in `call'
rails:   bundle/ruby/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
rails:   bundle/ruby/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'
rails:   bundle/ruby/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
rails:   bundle/ruby/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
rails:   /opt/passenger/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
rails:   /opt/passenger/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
rails:   /opt/passenger/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
rails:   /opt/passenger/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
rails: /opt/passenger/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by psunix** [comment]
es hat noch weitere 404 errors: 

`rails: ActionController::RoutingError (No route matches [GET] "/assets/chosen-sprite.png")`

die Errors werden nicht nach Errbit reportet da 404 errors generell gefiltert werden.

**Comment by kronn** [comment]
AFAIK wird die statische Datei bevorzugt vom Webserver ausgeliefert. Wenn sie nicht existiert, wird der Request an Rails weitergegeben.

**Comment by psunix** [comment]
@kronn und @psunix haben sicher kurz darüber ausgetauscht. das mit dem 404 error ist eigentilch standard verhalten und grundsätzlich ok.
Sinnvoll wäre sicher das man die fehlenden Files die dauernd angefragt werden noch ergänzt in den Assets. Das ist eben z.B. apple-touch-icon-precomposed.png

**Comment by RolandStuder** [comment]
Markiere dieses Issue als inaktiv.
