### ISSUE TITLE
Error in spawning new processes

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito#503]
Folgender Fehler trat nach einem Deployment mehrmals im Log auf. Allerdings wurde die Applikation schlussendlich doch gestartet.

```
[ E 2018-03-28 10:38:17.1559 68/Tm age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /opt/app-root/src: An error occurred while starting up the preloader.
--
  | apache:   Error ID: 2abb03ae
  | apache:   Error details saved to: /tmp/passenger-error-NENfSa.html
  | apache:   Message from application: undefined method `origin_user' for class `ErrorsController' (NameError)
  | apache:   /opt/app-root/src/app/controllers/errors_controller.rb:22:in `<class:ErrorsController>'
  | apache:   /opt/app-root/src/app/controllers/errors_controller.rb:10:in `<top (required)>'
  | apache:   /opt/app-root/src/bundle/ruby/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
  | apache:   /opt/app-root/src/bundle/ruby/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
  | apache:   /opt/app-root/src/bundle/ruby/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
  | apache:   /opt/app-root/src/bundle/ruby/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
  | apache:   /opt/app-root/src/bundle/ruby/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:360:in `require_or_load'
  | apache:   /opt/app-root/src/bundle/ruby/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:317:in `depend_on'
  | apache:   /opt/app-root/src/bundle/ruby/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:233:in `require_dependency'
  | apache:   /opt/app-root/src/bundle/ruby/gems/railties-4.2.8/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
  | apache:   /opt/app-root/src/bundle/ruby/gems/railties-4.2.8/lib/rails/engine.rb:471:in `each'
  | apache:   /opt/app-root/src/bundle/ruby/gems/railties-4.2.8/lib/rails/engine.rb:471:in `block in eager_load!'
  | apache:   /opt/app-root/src/bundle/ruby/gems/railties-4.2.8/lib/rails/engine.rb:469:in `each'
  | apache:   /opt/app-root/src/bundle/ruby/gems/railties-4.2.8/lib/rails/engine.rb:469:in `eager_load!'
  | apache:   /opt/app-root/src/bundle/ruby/gems/railties-4.2.8/lib/rails/engine.rb:346:in `eager_load!'
  | apache:   /opt/app-root/src/bundle/ruby/gems/railties-4.2.8/lib/rails/application/finisher.rb:56:in `each'
  | apache:   /opt/app-root/src/bundle/ruby/gems/railties-4.2.8/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
  | apache:   /opt/app-root/src/bundle/ruby/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
  | apache:   /opt/app-root/src/bundle/ruby/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
  | apache:   /opt/app-root/src/bundle/ruby/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
  | apache:   /opt/rh/rh-ruby22/root/usr/share/ruby/tsort.rb:226:in `block in tsort_each'
  | apache:   /opt/rh/rh-ruby22/root/usr/share/ruby/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
  | apache:   /opt/rh/rh-ruby22/root/usr/share/ruby/tsort.rb:429:in `each_strongly_connected_component_from'
  | apache:   /opt/rh/rh-ruby22/root/usr/share/ruby/tsort.rb:347:in `block in each_strongly_connected_component'
  | apache:   /opt/rh/rh-ruby22/root/usr/share/ruby/tsort.rb:345:in `each'
  | apache:   /opt/rh/rh-ruby22/root/usr/share/ruby/tsort.rb:345:in `call'
  | apache:   /opt/rh/rh-ruby22/root/usr/share/ruby/tsort.rb:345:in `each_strongly_connected_component'
  | apache:   /opt/rh/rh-ruby22/root/usr/share/ruby/tsort.rb:224:in `tsort_each'
  | apache:   /opt/rh/rh-ruby22/root/usr/share/ruby/tsort.rb:203:in `tsort_each'
  | apache:   /opt/app-root/src/bundle/ruby/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
  | apache:   /opt/app-root/src/bundle/ruby/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
  | apache:   /opt/app-root/src/bundle/ruby/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
  | apache:   /opt/app-root/src/bundle/ruby/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
  | apache:   /opt/app-root/src/config/environment.rb:5:in `<top (required)>'
  | apache:   config.ru:4:in `require'
  | apache:   config.ru:4:in `block in <main>'
  | apache:   /opt/app-root/src/bundle/ruby/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
  | apache:   /opt/app-root/src/bundle/ruby/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
  | apache:   config.ru:1:in `new'
  | apache:   config.ru:1:in `<main>'
  | apache:   /opt/passenger/src/helper-scripts/rack-preloader.rb:110:in `eval'
  | apache:   /opt/passenger/src/helper-scripts/rack-preloader.rb:110:in `preload_app'
  | apache:   /opt/passenger/src/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  | apache:   /opt/passenger/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  | apache:   /opt/passenger/src/helper-scripts/rack-preloader.rb:29:in `<main>'
  | apache:

```

**Comment by RolandStuder** [comment]
@amaierhofer Dann ist dies also schon gefixt, gemäss Rocket Chat
