### ISSUE TITLE
Build fails weil Rollenlabe nicht vergeben werden können

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#541]
```
Failures:

  1) Group Group::VereinMitglieder Group::VereinMitglieder::Ehrenmitglied has an own label
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: value != "Rolle"
            got: "Rolle"

       (compared using ==)
     Shared Example Group: "group types" called from ./spec/models/group_spec.rb:12
     # /var/lib/jenkins/workspace/hitobito-sbv/hitobito/spec/support/group_types_examples.rb:75:in `block (6 levels) in <top (required)>'
     # /var/lib/jenkins/workspace/hitobito-sbv/hitobito/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<main>'

  2) Group Group::RootEhrenmitglieder Group::RootEhrenmitglieder::Ehrenmitglied has an own label
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: value != "Rolle"
            got: "Rolle"

       (compared using ==)
     Shared Example Group: "group types" called from ./spec/models/group_spec.rb:12
     # /var/lib/jenkins/workspace/hitobito-sbv/hitobito/spec/support/group_types_examples.rb:75:in `block (6 levels) in <top (required)>'
     # /var/lib/jenkins/workspace/hitobito-sbv/hitobito/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<main>'

Finished in 1.12 seconds (files took 16.17 seconds to load)
266 examples, 2 failures

Failed examples:

rspec ./spec/models/group_spec.rb[1:25:7:3] # Group Group::VereinMitglieder Group::VereinMitglieder::Ehrenmitglied has an own label
rspec ./spec/models/group_spec.rb[1:9:5:3] # Group Group::RootEhrenmitglieder Group::RootEhrenmitglieder::Ehrenmitglied has an own label


```

**Comment by RolandStuder** [comment]
Auf PBS Int reproduzierbar, aber jeweils nur ein Mal direkt nach dem Login:

To reproduce:
- Log out
- Log In
- Versuche ein Rollenlabel zu ändern
- Neues Rollenlabel wird nicht vergeben.

**Comment by amaierhofer** [comment]
Build konnte ich fixen, das lag an fehlenden Übersetzungen. 

Das von dir  beschriebene Issue mit dem Vergeben von Labels auf Rollen auf der PBS Integration konnte ich nicht reproduzieren.

**Comment by RolandStuder** [comment]
Hier ein Cast, ich kann es konstnat reproduzieren, aber nur in einer neuen Session, mit erneutem Login: https://screencast.com/t/3JUpvlCGcH

**Comment by RolandStuder** [comment]
Ich kann es jetzt nicht mehr reproduzieren.
