### ISSUE TITLE
rake Versionskonflikt

### ISSUE THREAD

**Issue by throwException** [hitobito/hitobito#698]
Beim bundle tritt folgender Versionskonflikt auf:
```
rake aborted!
Gem::LoadError: You have already activated rake 12.3.0, but your Gemfile requires rake 11.3.0. Prepending `bundle exec` to your command may solve this.
/home/hitobito/hitobito/config/boot.rb:6:in `<top (required)>'
/home/hitobito/hitobito/config/application.rb:8:in `<top (required)>'
/home/hitobito/hitobito/Rakefile:12:in `<top (required)>'
(See full trace by running task with --trace)
```

Ich verwende folgendes Dockerfile:
```
FROM drecom/ubuntu-ruby:2.5.3

RUN locale-gen en_US.UTF-8
ENV LANG="en_US.UTF-8"
ENV LC_ALL="en_US.UTF-8"
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y libsqlite3-dev sphinxsearch

RUN useradd hitobito -m
WORKDIR /home/hitobito

RUN git clone --branch stable https://github.com/hitobito/hitobito
RUN git clone --branch stable https://github.com/hitobito/hitobito_generic

ADD Wagonfile /home/hitobito/hitobito/Wagonfile

WORKDIR /home/hitobito/hitobito

RUN bundle
```

Buby Version ist:
```
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
```

Was mache ich falsch?

**Comment by throwException** [comment]
Problem gelöst. Ruby 2.5.3 war zu neu. Mit ruby 2.2.10 gehts.
