### ISSUE TITLE
Transifex files pushen (4h)

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#772]
Die Locale files müssen regelmässig an transifex gepusht werdenn. Am besten geht das über die build jobs (wagons nicht vergessen). Aktuell fehlt am jenkins die transifex binary

```
rake app:tx:auth app:tx:push
require gems:   2.760000   1.240000   4.000000 (  4.315616)
require rails:   0.890000   0.290000   1.180000 (  3.007377)
tx push -s
require gems:   2.980000   1.130000   4.110000 (  7.472652)
Traceback (most recent call last):
  File "/usr/bin/tx", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: python-slugify
rake aborted!
```

**Comment by amaierhofer** [comment]
Transifex files werden jetzt jeweils beim Integrations deployment gepushed und gepullt.
