### ISSUE TITLE
App auf Ruby 2.5 aktualisieren (8h)

### ISSUE THREAD

**Issue by severinraez** [hitobito/hitobito#773]
Erst #759 erledigen, danach muss Deployment-seitig nur das Base-Image geändert und alle Builds getriggert werden.

**Comment by amaierhofer** [comment]
Aktuell besteht ein Problem beim Bauen vom Rails Image, auf Openshift gibt es folgende Fehlermeldung, nachdem alle gems installiert wurden 
```
I, [2019-12-17T14:28:56.184447 #27352]  INFO -- : * wirble-0.1.3.gem
I, [2019-12-17T14:28:57.585407 #27352]  INFO -- : ---> Installing application source ...
I, [2019-12-17T14:28:57.596332 #27352]  INFO -- : mv: cannot move '/tmp/src/.bundle' to './.bundle': File exists
I, [2019-12-17T14:28:59.624442 #27352]  INFO -- : error: build error: non-zero (13) exit code from docker-registry.default.svc:5000/hit-cevi-int/rails-sti-base@sha256:b9d9eb81d2f22e0f90b7a872b041264e47a68f6c806f21cbbdba9f247f8ac4fa
build.rb:213:in `build_status': wrong number of arguments (0 for 1) (ArgumentError)
	from build.rb:209:in `check_build!'
	from build.rb:28:in `run'
	from build.rb:254:in `<main>'
```

Lokal komme ich leidder nicht so weit, da hänge ich bei 

```
 {devel} ose_composition_cevi$  s2i build . hit-test
Submodule 'hitobito' (https://github.com/hitobito/hitobito.git) registered for path 'hitobito'
Submodule 'hitobito_cevi' (https://github.com/hitobito/hitobito_cevi.git) registered for path 'hitobito_cevi'
Submodule 'hitobito_youth' (https://github.com/hitobito/hitobito_youth.git) registered for path 'hitobito_youth'
Cloning into '/tmp/s2i652207541/upload/src/hitobito'...
Cloning into '/tmp/s2i652207541/upload/src/hitobito_cevi'...
Cloning into '/tmp/s2i652207541/upload/src/hitobito_youth'...
Submodule path 'hitobito': checked out 'bfa5958f2fe0c6740ac9716782292a2a3fd01740'
Submodule path 'hitobito_cevi': checked out '59b6f63a8e107b173239b051b6ce4faf8def8ec5'
Submodule path 'hitobito_youth': checked out 'feeb42115255674645c74a079a49c8f0da6b4cb3'
fatal: Not a git repository (or any of the parent directories): .git
Build failed
ERROR: An error occurred: non-zero (13) exit code from hit-test
```

**Comment by amaierhofer** [comment]
Hab das s2i assembly script angepasst, siehe b7cb4cb0, jetzt sind wir einen Schritt weiter und scheitern aktuell an transifex

```
Integration build: Pulling transifex translations.
** Invoke tx:pull (first_time)
** Execute tx:pull
tx pull -f
rake aborted!
Command failed with status (127): [tx pull -f...]
```

**Comment by severinraez** [comment]
Da fehlt doch ein rake vor dem "tx pull -f" ? https://stackoverflow.com/questions/1763156/127-return-code-from

**Comment by amaierhofer** [comment]
Demo läuft jetzt bereits auf ruby-2.5.5, die anderen Instanzen werden sukzessive upgedatet.
